version: "2.3"

services:
    postgres:
        container_name: service-postgres
        image: postgres:12
        environment:
          - POSTGRES_DB=dummy_bookstore_book_shop
          - POSTGRES_USER=user
          - POSTGRES_PASSWORD=password
        ports:
          - 5432
        volumes:
          - ./postgresql/schemas:/docker-entrypoint-initdb.d
          - ./.pgdata:/var/lib/postgresql/data
        networks:
          - postgres

    dummy_bookstore-container:
        image: ghcr.io/userver-framework/ubuntu-userver-build-base:v1
        privileged: true
        environment:
          - POSTGRES_DB=dummy_bookstore_book_shop
          - POSTGRES_USER=user
          - POSTGRES_PASSWORD=password
          - PREFIX=${PREFIX:-~/.local}
          - CC
          - CCACHE_DIR=/dummy_bookstore/.ccache
          - CCACHE_HASHDIR
          - CCACHE_NOHASHDIR
          - CCACHE_PREFIX
          - CCACHE_SIZE
          - CMAKE_OPTS
          - CORES_DIR=/cores
          - CXX
          - MAKE_OPTS
          - CMAKE_OPTIONS
        volumes:
          - .:/dummy_bookstore:rw
          - ./third_party/userver/tools/docker:/tools:ro
          - ${TC_CORES_DIR:-./.cores}:/cores:rw
          - ./static:/var/www/static:rw
        ports:
          - 8080:8080
        working_dir: /dummy_bookstore
        entrypoint:
          - /tools/run_as_user.sh
        depends_on:
          - postgres
          - pgadmin
        networks:
          - postgres

    pgadmin:
      container_name: pgadmin_container
      image: dpage/pgadmin4:7.2
      environment:
          PGADMIN_DEFAULT_EMAIL: "pguser@example.com"
          PGADMIN_DEFAULT_PASSWORD: "pgadminpwd"
          PGADMIN_CONFIG_SERVER_MODE: "False"
      volumes:
          - pgadmin-data:/var/lib/pgadmin
          - ./postgresql:/docker-entrypoint-initdb
      ports:
          - "5050:80"
      restart: unless-stopped
      deploy:
          resources:
              limits:
                  cpus: '0.5'
                  memory: 1G
      networks:
          - postgres

networks:
    postgres:
        driver: bridge

volumes:
    pgadmin-data: