// sql.hpp
#include <userver/storages/postgres/query.hpp>

// ATTENTION: FILE AUTOGENERATED

const storages::postgres::Query kInsertBooks{
    R"(INSERT INTO TABLE bookshop.books VALUES (123, 234))",
    storages::postgres::Query::Name{"insert_books"}};

// simple select
// double comment
// book table
const storages::postgres::Query kGetBooks{
    R"(SELECT id, title 
FROM bookshop.books )",
    storages::postgres::Query::Name{"get_books"}};
